---
:ems:
  :ems_foreman:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:ems_refresh:
  :foreman_configuration:
    :inventory_object_refresh: false
:http_proxy:
  :foreman:
    :host:
    :password:
    :port:
    :user:
